[workspace]
resolver = "2"
members = [
  "packages/ui",
  "packages/core",
  "packages/web",
  "packages/desktop",
  "packages/mobile",
]

[workspace.dependencies]
dioxus = { version = "0.7.1" }

# workspace
ui = { path = "packages/ui" }
core = { path = "packages/core" }
